<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Tript.Recorder</RootNamespace>
    <AssemblyName>Tript.Recorder</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tript.Core\Tript.Core.csproj" />
    <ProjectReference Include="..\Tript.Detection\Tript.Detection.csproj" />
    <ProjectReference Include="..\Tript.Obs\Tript.Obs.csproj" />
    <ProjectReference Include="..\Tript.Settings\Tript.Settings.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Tript.Recorder.Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Tript.App</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
