<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Tript.Media</RootNamespace>
    <AssemblyName>Tript.Media</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tript.Core\Tript.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Tript.Media.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
