<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Tript.ModelValidator</RootNamespace>
    <AssemblyName>Tript.ModelValidator</AssemblyName>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Tript.Detection/Tript.Detection.csproj" />
  </ItemGroup>
</Project>
